[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "HidMart"
version = "1.0.0"
description = "Python library for building Bale bots"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}

dependencies = [
    "requests>=2.28.0"
]

[tool.setuptools.packages.find]
include = ["hidmart*"]